---
title: "R Notebook"
output: html_notebook
---
 
## Candy Halloween Horror Hierachy

#Wrote the new clean data into a new folder.
# Revised the joins function to consider what needed to answer key questions
#Decided to complete a bind to create megadate and then answer the questions.
#Need to clean again. Back again to the dataset and consider the cleaning
#Cleaned the NA from the age column. But realised now that there are characted and numbers in the columns (providing a drop down menu of ages would have stopped rougu characted date appearing in this column)

###Analysis Questions




1.4.1
Q1.What is the total number of candy ratings given across the three years.
(Number of candy ratings, not the number of raters. Don’t count missing values)

#so this requires to count the number of ratings in each column
mega data
clear na
sum for each column


Q2 What was the average age of people who are NOT going out trick or treating?
#split into two parts
#all people who are answer yes to the trick and treat question
#and then the mean of the age from this group


A tibble: 1 × 1
  mega_cleanb
        <dbl>
1          NA
#Warning message:
#In mean.default(how_old_are_you) :
  #argument is not numeric or logical: returning NA
#But this had run and would allow me to turn the column to numeric and filtering the NA values
  
  
Warning message:
Problem while computing `how_old_are_you = as.numeric(how_old_are_you)`.
ℹ NAs introduced by coercion 


# then selected out the No's


    
        # mega_data%>%
   mutate(how_old_are_you = as.numeric(how_old_are_you))%>%
    filter(q1_going_out == "No")%>%
   mutate(average_age = mean(how_old_are_you))%>%
   select(average_age)
 
 This provided the average age of 38.9 years.   
    
Q3What was the average age of people who are ARE not going trick or treating?


mega_data%>%
   mutate(how_old_are_you = as.numeric(how_old_are_you))%>%
   filter(q1_going_out == "Yes")%>%
   mutate(average_age = mean(how_old_are_you, na.rm = TRUE))%>%
   select(average_age)

This provided the answer "infinity" so R telling me that that calculation is not defined (somewhere in the data set there is a really long number)
this is counting the NA as well

#So then needed to filter out the respondent who may have put in a very long number (2000)

treater_averageage <-mega_datanoinfinity%>%
  mutate(how_old_are_you = as.numeric(how_old_are_you))%>%
  filter(q1_going_out == "Yes")%>%
  filter(how_old_are_you < 100)%>%
  mutate(average_age = mean(how_old_are_you, na.rm = TRUE))%>%
  select(average_age)

This then gave me the average of 33.6


Q4For each of joy, despair and meh, which candy bar received the most of these ratings?

Q5How many people rated Starburst as despair?
For the next three questions, count despair as -1, joy as +1, and meh as 0.

Q6What was the most popular candy bar by this rating system for each gender in the dataset ?

Q7What was the most popular candy bar in each year?

Q8What was the most popular candy bar by this rating for people in US, Canada, UK, and all other countries?